### ISSUE TITLE
Links and Images

### ISSUE THREAD

**Issue by shimetoya** [freeversity/freeversity.github.io#2]
1. https://freeversity.github.io/chapters/4/tasks/4
![photo_2022-07-03_22-55-20](https://user-images.githubusercontent.com/19570758/177055334-1c78889c-30e0-48e1-b1de-b7faa0d14015.jpg)
result check isnt working
2. https://freeversity.github.io/chapters/4/tasks/5
![photo_2022-07-03_22-56-11](https://user-images.githubusercontent.com/19570758/177055485-9d507507-2e6a-46f2-bf1b-941dc12b00fe.jpg)
result check isnt working
3. https://freeversity.github.io/chapters/4/tasks/14
missed text
4. mix ask 19 and 20 
https://freeversity.github.io/chapters/4/tasks/19
https://freeversity.github.io/chapters/4/tasks/20
![photo_2022-07-03_23-08-40](https://user-images.githubusercontent.com/19570758/177055650-efa83397-8132-4c04-b538-9d9e6b13089f.jpg)
5. extra world "Москва" :)
https://freeversity.github.io/chapters/4/tasks/12
https://freeversity.github.io/chapters/4/tasks/13
6. incorrect link (404 File not found)
https://freeversity.github.io/chapters/4/tasks/20

**Comment by freeversity** [comment]
`extra world "Москва" :)`

all stuff related to rusnya will be fixed during translation :)
