### ISSUE TITLE
microgrids-v1

### ISSUE THREAD

**Issue by shimetoya** [freeversity/freeversity.github.io#4]
1. missed image
https://freeversity.github.io/chapters/8/tasks/19

2. different match percentage on different devices
https://freeversity.github.io/chapters/8/tasks/7
![photo_2022-07-09_16-58-47](https://user-images.githubusercontent.com/19570758/178109053-64eb01d1-fdf2-41df-9dac-25779033104b.jpg)
![photo_2022-07-09_16-58-53](https://user-images.githubusercontent.com/19570758/178109069-989a36c8-f96c-4eaf-b506-b37f29a59931.jpg)

**Comment by freeversity** [comment]
@shimetoya could you provide more info on used devices?

**Comment by freeversity** [comment]
done
